### ISSUE TITLE
osx mysterious failure

### ISSUE THREAD

**Issue by jbenet** [davecheney/graphpkg#3]
(With more time, i'd dig more into this, but at least this note might help another traveller.)

In osx (go 1.3), simply installing `graphpkg` with 

```
go get github.com/davecheney/graphpkg
```

And then running

```
graphpkg net
```
exited (0) with no output. `github.com/davecheney/graphpkg` uses  `github.com/pkg/browser` to view things so something is going wrong between the current version of `browser`, osx's `open`, and possibly my browser (Chrome), and not telling us. I changed:

```go
go browser.OpenReader(out)

// to

go func() {
	err := browser.OpenReader(out)
	check(err)
}()
```

to try and capture the error, but then it magically worked! What changed? I did build `github.com/pkg/browser/examples/Open` so maybe that put some component in the right place. If you run into a similar problem try:

```
go get github.com/pkg/browser
go build github.com/pkg/browser/example/Open
```

**Comment by brycefisher** [comment]
Ditto here... go 1.5.1

**Comment by jmhodges** [comment]
Nah, turns out this is just a race that shows up more often in OS X.

The cmd.Wait() returns sometimes before OpenReader finishes its work. Since the OpenReader is a non-main goroutine, the process exits. OpenReader gets about halfway through the function most of the time.

I'm posting a PR to fix this.
